### ISSUE TITLE
Font weight not generated with removeFallbacks plugin

### ISSUE THREAD

**Issue by fknop** [Arthie/xwind#18]
With the removeFallbacks plugin, font-weight is not generated anymore since the update to tailwindcss 2.0 and xwind.

With the removeFallbacks plugin, tw`font-bold` emits an empty fontWeight object

**Comment by Arthie** [comment]
I wasn't able to reproduce this bug, can you provide more info?

Do you have babel caching enabled from babel-loader or next-babel-loader?
If so try manually deleting the cached babel files and rebuilding your project.

**Comment by fknop** [comment]
I'm using CRA which comes with babel and babel macros included. 
I tried deleting node_modules/.cache but without success.
I'm gonna try to reinstall the entire node modules directory.

**Comment by fknop** [comment]
I tried deleting the node_modules directory but with no success.
For more info: CRA + xwind/macro

**Comment by fknop** [comment]
It might be related to generated outputs being numbers. I tried with leading-none which generated 1. It didn't generate anything, however, leading-10 generates properly 2.5rem

**Comment by Arthie** [comment]
@fknop Thanks! I was able to reproduce the bug by creating a CRA project. I'm releasing a fix soon!
Yes, you are correct the fallback plugin didn't handle numbers correctly.

**Comment by Arthie** [comment]
@fknop should be fixed in the latest version (0.7.4)!
Don't forget to delete the `node_modules/.cache` again to get a clean build.
I recommend deleting the cache after `tailwind.config.js` changes or after updating packages until babel adds this [PR](https://github.com/babel/babel/pull/11741) to fix issue [#8497](https://github.com/babel/babel/issues/8497).
