### ISSUE TITLE
Why must xwind be imported first before @emotion/styled ??

### ISSUE THREAD

**Issue by GZLiew** [Arthie/xwind#19]
Hi I was migrating to tailwindcss v2 when I stumbled upon your library

I was using @tailwindcssinjs/macro previous

so while migrating I encountered the following error.

![image](https://user-images.githubusercontent.com/43195293/100682777-cad33780-33b1-11eb-86f8-0c012c0c261b.png)

So after few days of figuring out the solution. I finally found out that the import order actually matters in this case

Here's a reproducible demo I forked from your nextjs sample
https://codesandbox.io/s/xwind-simple-example-forked-8zu41?file=/components/Button/Button.styles.ts

if you were to reverse the import order, it wont throw an error anymore.

**Comment by Arthie** [comment]
Hello, interesting question!

@tailwindcssinjs/macro was rewritten and rebranded to xwind. @tailwindcssinjs/macro was a proof of concept and xwind is the result of what I learned from creating @tailwindcssinjs/macro. xwind has all the features of @tailwindcssinjs/macro and more.
Feel free to let me know if there were any other problems migrating @tailwindcssinjs/macro to xwind.

**Now to your question:**
The order of when babel runs plugins is indeed important. We are using custom syntax and functionality in our javascript files to make it easy to use tailwind classes in javascript. This functionality is transpiled by the xwind babel plugin to javascript.
It seems like in this case the order in which babel plugin gets to run first depends on the order of when it's imported.
The xwind plugin has to be run before the emotion plugin since emotion has no idea how to use the xwind syntax.

Thanks for sharing a codesandbox! This made it easy to test!

I just started a new job this week so I'm very busy at the moment.
I'll try to take some time this weekend to see if I can make it possible to always run the xwind babel plugin first.
Adding this to the docs would be helpful as well!

**Comment by GZLiew** [comment]
Thanks for the reply @Arthie the library still works so thats fine for now.

Thanks for creating this library.

I dont mind making a PR if I am able to find a solution for this as well. This is quite a great tool.

Congratulation on the new job as well. All the best to you
