### ISSUE TITLE
typescript-xwind-plugin: Support tw="" syntax from twin.macro

### ISSUE THREAD

**Issue by lopezjurip** [Arthie/xwind#20]
I wonder if is possible to support the `tw=` syntax from [twin.macro](https://github.com/ben-rogerson/twin.macro) to gain full VSCode support for that library.
```js
import "twin.macro";
const Input = () => <input tw="border hover:border-black" />; // No IntelliSense
const Input = () => <input css={tw`border hover:border-black`} />; // This has IntelliSense ✅
```

Everything else works perfectly, great job!

**Comment by Arthie** [comment]
Thought about this for a while I'm sure it's possible but I can't justify spending time to add and maintain features that xwind doesn't support.

Feel free to fork the typescript-xwind-plugin. Just be aware typescript language service plugins are no joke and limiting in what's possible. I've been thinking about rewriting the extension as a language server this would be easier to maintain and allow more features.

A custom [JSX Transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) for xwind is something I have thought about but I currently don't have to time to experiment further. 

The reason xwind doesn't have a jsx tw prop is because I want to keep the library simpler and seem less magical.
xwind objecstyles mode also supports any CSS-in-JS solution adding this feature would limit it to emotion, styled-components ...

**Comment by lopezjurip** [comment]
Thanks for your reply @Arthie, since this syntax is possible `css={tw` I don't think it is an urgency to support `tw=""`
